Map<dynamic, dynamic> inEle;
var qQuTraceAuth;
var qFirstName;
var qLastName;
var qUserID;
var qUserName;
var qUserCellNumber;
var qUserEmail;
var qCompanyID;
var qEntTypeID;
var qShopID;
String respStatus = "";
String respText = "";